### ISSUE TITLE
Exceptions and crashes on Android devices

### ISSUE THREAD

**Issue by konstantin-saetskiy-voodoo** [Lofelt/NiceVibrations#35]
Hey!
I'm getting a lot of exceptions on Android devices using Feel (NiceVibrations) v.3.1.3 package using Unity 2021.3.28f1:

```
Non-fatal Exception: java.lang.Exception: NullReferenceException : Object reference not set to an instance of an object.
       at Lofelt.NiceVibrations.JNIHelpers.Call(Lofelt.NiceVibrations.JNIHelpers)
       at Lofelt.NiceVibrations.HapticController.Play(Lofelt.NiceVibrations.HapticController)
       at Lofelt.NiceVibrations.HapticPatterns.PlayEmphasis(Lofelt.NiceVibrations.HapticPatterns)
```

```
Non-fatal Exception: java.lang.Exception: NullReferenceException : Object reference not set to an instance of an object.
       at Lofelt.NiceVibrations.JNIHelpers.Call(Lofelt.NiceVibrations.JNIHelpers)
       at Lofelt.NiceVibrations.HapticController.Loop(Lofelt.NiceVibrations.HapticController)
       at Lofelt.NiceVibrations.HapticPatterns.PlayEmphasis(Lofelt.NiceVibrations.HapticPatterns)
```

```
Non-fatal Exception: java.lang.Exception: NullReferenceException : Object reference not set to an instance of an object.
       at Lofelt.NiceVibrations.JNIHelpers.Call(Lofelt.NiceVibrations.JNIHelpers)
       at Lofelt.NiceVibrations.HapticController.Load(Lofelt.NiceVibrations.HapticController)
       at Lofelt.NiceVibrations.HapticController.Load(Lofelt.NiceVibrations.HapticController)
       at Lofelt.NiceVibrations.HapticPatterns.PlayEmphasis(Lofelt.NiceVibrations.HapticPatterns)
```

```
Non-fatal Exception: java.lang.Exception: NullReferenceException : Object reference not set to an instance of an object.
       at Lofelt.NiceVibrations.JNIHelpers.Call(Lofelt.NiceVibrations.JNIHelpers)
       at Lofelt.NiceVibrations.HapticPatterns.PlayConstant(Lofelt.NiceVibrations.HapticPatterns)
```

and crashes:

```
Caused by java.util.concurrent.TimeoutException: com.lofelt.haptics.LofeltHaptics.finalize() timed out after 10 seconds
       at com.lofelt.haptics.LofeltHaptics.destroy(LofeltHaptics.java)
       at com.lofelt.haptics.LofeltHaptics.finalize(LofeltHaptics.java:242)
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:339)
       at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:324)
       at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:300)
       at java.lang.Daemons$Daemon.run(Daemons.java:145)
       at java.lang.Thread.run(Thread.java:1012)
```

```
Caused by java.util.concurrent.TimeoutException: com.lofelt.haptics.LofeltHaptics.finalize() timed out after 10 seconds
       at com.lofelt.haptics.LofeltHaptics.destroy(LofeltHaptics.java)
       at com.lofelt.haptics.LofeltHaptics.finalize(LofeltHaptics.java:242)
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:319)
       at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:306)
       at java.lang.Daemons$Daemon.run(Daemons.java:140)
       at java.lang.Thread.run(Thread.java:1012)
```

Do you have any solution for this?

**Comment by cihadturhan** [comment]
I have the same problem. I only use
```
HapticPatterns.PlayPreset(HapticPatterns.PresetType.Success);
```
on Android.

**Comment by cihadturhan** [comment]
It's fixed when I added some delay after an ad is shown.

**Comment by cihadturhan** [comment]
I see the same problem in another part of the project.
Is there a fix for null check instead of me adding delays everywhere to ensure it's initialized?

**Comment by cihadturhan** [comment]
@mzzndr Did you gave up the support of Nice Vibrations?
I'm still getting a bunch of crash reports.

Is the NV in Feel package has the same version? If that has an updated library, I can buy it just for the sake of this crash fix.


```
   Fatal Exception: java.lang.Exception: NullReferenceException : Object reference not set to an instance of an object.
       at Lofelt.NiceVibrations.JNIHelpers.Call(Lofelt.NiceVibrations.JNIHelpers)
       at Lofelt.NiceVibrations.JNIHelpers.Call(Lofelt.NiceVibrations.JNIHelpers)
       at _Project.Scripts.SongListAdapter+<>c__DisplayClass9_1.<CreateViewsHolder>g__OnUnlockClick|1(_Project.Scripts.SongListAdapter+<>c__DisplayClass9_1)
       at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext)
       at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run(System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner)
       at Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult].TrySetResult(Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1[TResult])
       at Cysharp.Threading.Tasks.UniTask+DelayPromise.MoveNext(Cysharp.Threading.Tasks.UniTask+DelayPromise)
       at Cysharp.Threading.Tasks.Internal.PlayerLoopRunner.RunCore(Cysharp.Threading.Tasks.Internal.PlayerLoopRunner)
       at Lofelt.NiceVibrations.JNIHelpers:Call(Lofelt.NiceVibrations)
       at _Project.Scripts.<<CreateViewsHolder>g__OnUnlockClick|1>d:MoveNext(_Project.Scripts)
       at System.Runtime.CompilerServices.MoveNextRunner:Run(System.Runtime.CompilerServices)
       at Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetResult(Cysharp.Threading.Tasks)
       at Cysharp.Threading.Tasks.DelayPromise:MoveNext(Cysharp.Threading.Tasks)
       at Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:RunCore(Cysharp.Threading.Tasks.Internal)
```

**Comment by reunono** [comment]
@cihadturhan Feel supports multiple third party libraries, NV included. The version in Feel is the exact same as on this repository. What Feel provides on top is a set of tools to target the API. Do not buy it hoping it would solve that error, it's the same code.

**Comment by mzzndr** [comment]
Hi @cihadturhan 
I tried to run the Android demo and I see no crashes with this setup.
Can you recreate the crash in the demo app or in a quick sample app so that I can investigate it on my end?

**Comment by cihadturhan** [comment]
> Hi @cihadturhan I tried to run the Android demo and I see no crashes with this setup. Can you recreate the crash in the demo app or in a quick sample app so that I can investigate it on my end?

Unfortunately I can't reproduce the crash on my devices, but the problem exists in many other devices. Just to name a few:

<table>
<tr>
<td>

![image](https://github.com/user-attachments/assets/a654f45c-f400-4956-bd6a-72f9e312cb31)

</td>
<td>

![image](https://github.com/user-attachments/assets/6858fe55-c322-4217-8eac-c20730ed1bbb)

</td>
<td>

![image](https://github.com/user-attachments/assets/5625decc-76ec-4bf5-8f9e-46de3b2ba2ff)

</td>
</tr>
</table>

I'd like to open a PR which at least should check for null expressions if you'd approve.

**Comment by mzzndr** [comment]
Sure, I'd be happy to look at it.

**Comment by cihadturhan** [comment]
> Sure, I'd be happy to look at it.

Ok I think I understood why. The problem is, I use Applovin for ad mediation and it sometimes calls callbacks in threads other than main (I've had many issues with this before)

I guess when `HapticPatterns.PlayPreset` gets called in other threads, it couldn't access to the variables and throws `NullReferenceException`. Correct?

If that's the case, I'll try to fix that in my code as it's not related to NV.
